-- 위험물검사 고객지원: 관리자·콘텐츠·파일 저장소 초기 설정
-- Supabase Dashboard > SQL Editor에서 전체 실행해도 되고,
-- GitHub Integration의 production 배포로 migration을 적용해도 됩니다.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.site_config (
  id smallint primary key default 1 check (id = 1),
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  category text not null default '기타',
  title text not null,
  summary text not null default '',
  cause text not null default '',
  action text not null default '',
  standard text not null default '',
  status text not null default '보완' check (status in ('보완', '부적합')),
  published boolean not null default true,
  before_image_path text,
  after_image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.manuals (
  id bigint generated by default as identity primary key,
  category text not null default '기타',
  title text not null,
  summary text not null default '',
  body text not null default '',
  faq boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  category text not null default '기타',
  title text not null,
  description text not null default '',
  file_path text not null,
  file_name text not null,
  file_type text not null default 'application/octet-stream',
  file_size bigint not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_config enable row level security;
alter table public.cases enable row level security;
alter table public.manuals enable row level security;
alter table public.resources enable row level security;

drop policy if exists "admin reads own role" on public.admin_users;
create policy "admin reads own role" on public.admin_users
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "public reads site config" on public.site_config;
create policy "public reads site config" on public.site_config
  for select to anon, authenticated using (true);

drop policy if exists "admin updates site config" on public.site_config;
create policy "admin updates site config" on public.site_config
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public reads published cases" on public.cases;
create policy "public reads published cases" on public.cases
  for select to anon, authenticated using (published or public.is_admin());

drop policy if exists "admin inserts cases" on public.cases;
create policy "admin inserts cases" on public.cases
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin updates cases" on public.cases;
create policy "admin updates cases" on public.cases
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin deletes cases" on public.cases;
create policy "admin deletes cases" on public.cases
  for delete to authenticated using (public.is_admin());

drop policy if exists "public reads published manuals" on public.manuals;
create policy "public reads published manuals" on public.manuals
  for select to anon, authenticated using (published or public.is_admin());

drop policy if exists "admin inserts manuals" on public.manuals;
create policy "admin inserts manuals" on public.manuals
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin updates manuals" on public.manuals;
create policy "admin updates manuals" on public.manuals
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin deletes manuals" on public.manuals;
create policy "admin deletes manuals" on public.manuals
  for delete to authenticated using (public.is_admin());

drop policy if exists "public reads published resources" on public.resources;
create policy "public reads published resources" on public.resources
  for select to anon, authenticated using (published or public.is_admin());

drop policy if exists "admin inserts resources" on public.resources;
create policy "admin inserts resources" on public.resources
  for insert to authenticated with check (public.is_admin());

drop policy if exists "admin updates resources" on public.resources;
create policy "admin updates resources" on public.resources
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin deletes resources" on public.resources;
create policy "admin deletes resources" on public.resources
  for delete to authenticated using (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.site_config, public.cases, public.manuals, public.resources to anon, authenticated;
grant insert, update, delete on public.cases, public.manuals, public.resources to authenticated;
grant update on public.site_config to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit)
values ('public-assets', 'public-assets', true, 31457280)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

drop policy if exists "public reads public assets" on storage.objects;
create policy "public reads public assets" on storage.objects
  for select to anon, authenticated using (bucket_id = 'public-assets');

drop policy if exists "admin uploads public assets" on storage.objects;
create policy "admin uploads public assets" on storage.objects
  for insert to authenticated with check (bucket_id = 'public-assets' and public.is_admin());

drop policy if exists "admin updates public assets" on storage.objects;
create policy "admin updates public assets" on storage.objects
  for update to authenticated using (bucket_id = 'public-assets' and public.is_admin())
  with check (bucket_id = 'public-assets' and public.is_admin());

drop policy if exists "admin deletes public assets" on storage.objects;
create policy "admin deletes public assets" on storage.objects
  for delete to authenticated using (bucket_id = 'public-assets' and public.is_admin());

insert into public.site_config (id, config)
values (1, jsonb_build_object(
  'organization', 'KFI 한국소방산업기술원',
  'siteTitle', '위험물검사 고객지원',
  'navHome', '홈',
  'navSchedule', '검사시기',
  'navProcedure', '검사절차',
  'navCases', '품질사례',
  'navManual', 'E-매뉴얼',
  'navResources', '양식자료',
  'navAdmin', '관리자',
  'heroEyebrow', '검사 준비부터 개선까지',
  'heroTitle', '위험물검사',
  'heroAccent', '안심동행',
  'heroText', '고객의 입장에서 어렵던 검사정보를 시기별로 쉽고 정확하게 안내합니다.',
  'scheduleTitle', '위험물시설 검사시기 안내',
  'scheduleText', '후배 직원의 검사시기 안내 기능을 완성한 뒤 이곳에 연결합니다.',
  'scheduleCardText', '업체별 검사대상 탱크와 검사기한을 안전하게 확인합니다.',
  'procedureTitle', '검사대상·절차 안내',
  'procedureText', '후배 직원의 검사절차 판정 기능을 현재 디자인에 연결할 예정입니다.',
  'procedureCardText', '시설과 공사조건에 맞는 검사종류와 준비절차를 알아봅니다.',
  'casesTitle', '위험물시설 품질관리 사례집',
  'casesText', '보완·부적합 사례를 검색하고 발생원인과 개선방법을 확인합니다.',
  'casesCardText', '자주 발생하는 보완·부적합 사례와 개선방법을 찾아봅니다.',
  'manualTitle', '위험물탱크 E-매뉴얼',
  'manualText', '검사 매뉴얼과 FAQ를 검색하고 필요한 내용을 빠르게 확인합니다.',
  'manualCardText', '검사 매뉴얼과 자주 묻는 질문을 검색합니다.',
  'resourcesTitle', '유용한 양식·자료실',
  'resourcesText', '검사 준비에 필요한 양식과 참고자료를 누구나 내려받을 수 있습니다.',
  'resourcesCardText', '현장에서 바로 쓰는 양식과 체크리스트를 내려받습니다.',
  'footerNotice', '본 서비스는 이해를 돕기 위한 안내자료이며, 최종 적용은 관계 법령과 검사기준을 확인해 주세요.'
))
on conflict (id) do nothing;

insert into public.cases (category, title, summary, cause, action, standard, status, published)
select '안전성능검사', '방유제 균열 및 배수밸브 누수',
       '방유제의 균열과 배수밸브 밀폐불량으로 위험물 유출 방지기능이 저하된 사례',
       '장기간 사용에 따른 콘크리트 열화와 배수밸브 패킹 손상',
       '균열부 보수 후 수밀상태를 확인하고 배수밸브 패킹을 교체합니다.',
       '위험물안전관리법 시행규칙 별표 6', '부적합', true
where not exists (select 1 from public.cases);

insert into public.manuals (category, title, summary, body, faq, published)
select '검사 준비', '안전성능검사 준비서류',
       '검사 신청 전에 준비해야 할 주요 도면과 시험성적서를 확인합니다.',
       '신청서, 탱크 구조도, 용접상세도, 비파괴검사 계획서, 재료시험성적서 등 시설과 공사범위에 해당하는 자료를 준비해 주세요.',
       false, true
where not exists (select 1 from public.manuals);

-- 중요: 먼저 Dashboard > Authentication > Users에서 아래 이메일의 사용자를 만든 뒤 실행합니다.
-- 사용자 이메일: kfi2275@admin.example.com
insert into public.admin_users (user_id)
select id from auth.users where lower(email) = 'kfi2275@admin.example.com'
on conflict (user_id) do nothing;
