-- Preserve existing cases and photographs. Run before deploying the new UI.
begin;
create table if not exists public.casebook_cases (
 id bigint generated by default as identity primary key,
 case_no integer not null default 1, inspection_type text not null default '',
 title text not null default '', facility text not null default '',
 photo1_path text, photo2_path text, photo_caption text not null default '', photo_note text not null default '',
 standard_title text not null default '', standard_body text not null default '',
 cause_title text not null default '', cause_body text not null default '',
 action_body text not null default '', prevention_body text not null default '',
 sort_order integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
-- Only legacy rows receive the historic visible/reviewed defaults; future inserts are private.
alter table public.casebook_cases add column if not exists published boolean not null default true;
alter table public.casebook_cases add column if not exists review_status text not null default '검토완료';
alter table public.casebook_cases alter column published set default false;
alter table public.casebook_cases alter column review_status set default '검토대기';
alter table public.casebook_cases add column if not exists finding_type text not null default '';
alter table public.casebook_cases add column if not exists test_item text not null default '';
alter table public.casebook_cases add column if not exists source_uid text;
alter table public.casebook_cases add column if not exists source_row integer;
alter table public.casebook_cases add column if not exists source_sheet text not null default '';
alter table public.casebook_cases add column if not exists review_note text not null default '';
create unique index if not exists casebook_source_uid_unique on public.casebook_cases(source_uid);
do $$ begin
 if not exists (select 1 from pg_constraint where conrelid='public.casebook_cases'::regclass and conname='casebook_review_valid') then
  alter table public.casebook_cases add constraint casebook_review_valid check (review_status in ('검토대기','기준확인필요','검토완료') and (not published or review_status='검토완료'));
 end if;
end $$;
alter table public.casebook_cases enable row level security;
-- Restrictive policies prevent any legacy permissive policy from exposing drafts or allowing writes.
drop policy if exists casebook_read_guard on public.casebook_cases;
create policy casebook_read_guard on public.casebook_cases as restrictive for select to anon, authenticated using ((published and review_status='검토완료') or public.is_admin());
drop policy if exists casebook_read on public.casebook_cases;
create policy casebook_read on public.casebook_cases for select to anon, authenticated using ((published and review_status='검토완료') or public.is_admin());
drop policy if exists casebook_insert_guard on public.casebook_cases;
create policy casebook_insert_guard on public.casebook_cases as restrictive for insert to anon, authenticated with check(public.is_admin());
drop policy if exists casebook_update_guard on public.casebook_cases;
create policy casebook_update_guard on public.casebook_cases as restrictive for update to anon, authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists casebook_delete_guard on public.casebook_cases;
create policy casebook_delete_guard on public.casebook_cases as restrictive for delete to anon, authenticated using(public.is_admin());
drop policy if exists casebook_admin on public.casebook_cases;
create policy casebook_admin on public.casebook_cases for all to authenticated using(public.is_admin()) with check(public.is_admin());
grant select on public.casebook_cases to anon, authenticated;
grant insert,update,delete on public.casebook_cases to authenticated;
do $$ declare seq text; begin
 seq := pg_get_serial_sequence('public.casebook_cases','id');
 if seq is not null then execute format('grant usage,select on sequence %s to authenticated',seq); end if;
end $$;

create or replace function public.import_casebook_cases(entries jsonb)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare e jsonb; n integer; added integer:=0; refreshed integer:=0; row_index integer:=0; affected integer;
begin
 if not public.is_admin() then raise exception '관리자만 가져올 수 있습니다.'; end if;
 if entries is null or jsonb_typeof(entries)<>'array' or jsonb_array_length(entries)>2000 then raise exception '최대 2000건의 배열이 필요합니다.'; end if;
 -- One transaction: failure rolls back every row; serialize numbering with manual writers.
 lock table public.casebook_cases in share row exclusive mode;
 select coalesce(max(case_no),0) into n from public.casebook_cases;
 for e in select value from jsonb_array_elements(entries) loop
  row_index:=row_index+1;
  if coalesce(e->>'source_uid','') !~ '^[a-zA-Z0-9:_-]{8,160}$' or coalesce(trim(e->>'title'),'')='' or coalesce(e->>'inspection_type','') in ('','안전성능검사') or coalesce(e->>'finding_type','') not in ('보완','부적합') or coalesce((e->>'source_row')::integer,0)<2 then
   raise exception '가져오기 %행: 식별자, 제목, 검사구분, 보완·부적합, 원본 행을 확인하세요.', row_index;
  end if;
  if exists(select 1 from public.casebook_cases where source_uid=e->>'source_uid') then
   -- Re-import must never overwrite a human review or reset photos/publication.
   update public.casebook_cases set source_row=(e->>'source_row')::integer, source_sheet=coalesce(e->>'source_sheet','') where source_uid=e->>'source_uid';
   refreshed:=refreshed+1;
  else
   n:=n+1;
   insert into public.casebook_cases(case_no,sort_order,inspection_type,title,facility,standard_title,standard_body,cause_title,cause_body,action_body,prevention_body,finding_type,test_item,source_uid,source_row,source_sheet,review_note,review_status,published,photo1_path,photo2_path,photo_caption,photo_note)
   values(n,n,e->>'inspection_type',e->>'title',coalesce(e->>'facility',''),coalesce(e->>'standard_title',''),coalesce(e->>'standard_body',''),coalesce(e->>'cause_title',''),coalesce(e->>'cause_body',''),coalesce(e->>'action_body',''),coalesce(e->>'prevention_body',''),e->>'finding_type',coalesce(e->>'test_item',''),e->>'source_uid',(e->>'source_row')::integer,coalesce(e->>'source_sheet',''),coalesce(e->>'review_note',''),case when e->>'review_status'='기준확인필요' then '기준확인필요' else '검토대기' end,false,null,null,'','')
   on conflict(source_uid) do nothing;
   get diagnostics affected=row_count; added:=added+affected;
  end if;
 end loop;
 return jsonb_build_object('등록',added,'원본참조갱신',refreshed,'공개',0);
end $$;
revoke all on function public.import_casebook_cases(jsonb) from public, anon;
grant execute on function public.import_casebook_cases(jsonb) to authenticated;
commit;
